require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/controllers', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Controller. As you add validations to Controller, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Controller.create! valid_attributes
      get controllers_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      controller = Controller.create! valid_attributes
      get controller_url(controller)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_controller_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      controller = Controller.create! valid_attributes
      get edit_controller_url(controller)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Controller' do
        expect do
          post controllers_url, params: { controller: valid_attributes }
        end.to change(Controller, :count).by(1)
      end

      it 'redirects to the created controller' do
        post controllers_url, params: { controller: valid_attributes }
        expect(response).to redirect_to(controller_url(Controller.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Controller' do
        expect do
          post controllers_url, params: { controller: invalid_attributes }
        end.to change(Controller, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post controllers_url, params: { controller: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested controller' do
        controller = Controller.create! valid_attributes
        patch controller_url(controller), params: { controller: new_attributes }
        controller.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the controller' do
        controller = Controller.create! valid_attributes
        patch controller_url(controller), params: { controller: new_attributes }
        controller.reload
        expect(response).to redirect_to(controller_url(controller))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        controller = Controller.create! valid_attributes
        patch controller_url(controller), params: { controller: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested controller' do
      controller = Controller.create! valid_attributes
      expect do
        delete controller_url(controller)
      end.to change(Controller, :count).by(-1)
    end

    it 'redirects to the controllers list' do
      controller = Controller.create! valid_attributes
      delete controller_url(controller)
      expect(response).to redirect_to(controllers_url)
    end
  end
end
